services:
  - type: web
    name: guitar-fretboard-visualizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:8080
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
